[package]
name = "unlisp-llvm"
version = "0.1.0"
authors = ["oleh.palianytsia <oleh.palianytsia@protonmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
inkwell = { path = "../inkwell-fork" }

[build-dependencies]
cc = "1.0"
