[package]
name = "unlisp_rt"
version = "0.1.0"
authors = ["oleh.palianytsia <oleh.palianytsia@protonmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
unlisp_internal_macros = { path = "../internal_macros" }

[build-dependencies]
cc = "1.0"

[lib]
crate-type = ["rlib", "staticlib"]