[package]
name = "unlisp_rt_staticlib"
version = "0.1.0"
authors = ["oleh.palianytsia <oleh.palianytsia@protonmail.com>"]
edition = "2018"

[workspace]

[dependencies]
unlisp_rt = { path = "../unlisp_rt" }

[lib]
name = "unlisp_rt"
crate-type = ["staticlib"]